//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserManagement._Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserManagement._Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string ButtonUpdate {
            get {
                return ResourceManager.GetString("ButtonUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Please choose -.
        /// </summary>
        public static string DdlChoose {
            get {
                return ResourceManager.GetString("DdlChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string DdlEmpty {
            get {
                return ResourceManager.GetString("DdlEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500: An error has occured!.
        /// </summary>
        public static string Error500 {
            get {
                return ResourceManager.GetString("Error500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data deleted succesfully.
        /// </summary>
        public static string MessageDeletedSuccess {
            get {
                return ResourceManager.GetString("MessageDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saved succesfully.
        /// </summary>
        public static string MessageSavedSuccess {
            get {
                return ResourceManager.GetString("MessageSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid characters in the text only [A-Za-z0-9 \-/,.\çëčćđšžÇËČĆĐŠŽğışüöİĞIŞÜÖ].
        /// </summary>
        public static string ValidateMultiLangChars {
            get {
                return ResourceManager.GetString("ValidateMultiLangChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only A-Z, a-z, 0-9, -,. are allowed.
        /// </summary>
        public static string ValidateSPChars {
            get {
                return ResourceManager.GetString("ValidateSPChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only A-Z, a-z and 0-9 are allowed.
        /// </summary>
        public static string ValidationAlphanumeric {
            get {
                return ResourceManager.GetString("ValidationAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a currency format.
        /// </summary>
        public static string ValidationCurrencyFormat {
            get {
                return ResourceManager.GetString("ValidationCurrencyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number must have up to two decimal places..
        /// </summary>
        public static string ValidationDecimalTwoPlaces {
            get {
                return ResourceManager.GetString("ValidationDecimalTwoPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email format is invalid.
        /// </summary>
        public static string ValidationEmail {
            get {
                return ResourceManager.GetString("ValidationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type is not allowed OR the file size is too large.
        /// </summary>
        public static string ValidationFileMaxSizeType {
            get {
                return ResourceManager.GetString("ValidationFileMaxSizeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type should be:.
        /// </summary>
        public static string ValidationFileType {
            get {
                return ResourceManager.GetString("ValidationFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value for {0} must be between {1} and {2}..
        /// </summary>
        public static string ValidationIntegerRange {
            get {
                return ResourceManager.GetString("ValidationIntegerRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format characters.
        /// </summary>
        public static string ValidationInvalidEmailCharacters {
            get {
                return ResourceManager.GetString("ValidationInvalidEmailCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file.
        /// </summary>
        public static string ValidationInvalidFile {
            get {
                return ResourceManager.GetString("ValidationInvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address only allows 0-9 and ..
        /// </summary>
        public static string ValidationIPFormat {
            get {
                return ResourceManager.GetString("ValidationIPFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid BBAN entered.
        /// </summary>
        public static string ValidationKosovoBBAN {
            get {
                return ResourceManager.GetString("ValidationKosovoBBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid RKS ID entered.
        /// </summary>
        public static string ValidationKosovoPersonalNo {
            get {
                return ResourceManager.GetString("ValidationKosovoPersonalNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RKS ID Algorithm fail.
        /// </summary>
        public static string ValidationKosovoPersonalNoAlgo {
            get {
                return ResourceManager.GetString("ValidationKosovoPersonalNoAlgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kosovo Mobile Phone No Invalid.
        /// </summary>
        public static string ValidationKosovoPhoneNo {
            get {
                return ResourceManager.GetString("ValidationKosovoPhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max file size should be (bytes):.
        /// </summary>
        public static string ValidationMaxFileSize {
            get {
                return ResourceManager.GetString("ValidationMaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be from {2} to {1} characters long.
        /// </summary>
        public static string ValidationMaximumLength {
            get {
                return ResourceManager.GetString("ValidationMaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid MSSQL database name characters entered.
        /// </summary>
        public static string ValidationMSSQLDatabaseName {
            get {
                return ResourceManager.GetString("ValidationMSSQLDatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} range must be between {1} and {2}.
        /// </summary>
        public static string ValidationOutOfRange {
            get {
                return ResourceManager.GetString("ValidationOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string ValidationPasswordRequired {
            get {
                return ResourceManager.GetString("ValidationPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password and conformation do not match.
        /// </summary>
        public static string ValidationPasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("ValidationPasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have at least one uppercase letter, one lowercase letter, one digit, and one special character..
        /// </summary>
        public static string ValidationPasswordStrength {
            get {
                return ResourceManager.GetString("ValidationPasswordStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Windows path characters entered.
        /// </summary>
        public static string ValidationPathChars {
            get {
                return ResourceManager.GetString("ValidationPathChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only a-zA-ZçÇëËčČćĆđĐšŠžŽĞğÖöŞşÜüIıİi are allowed.
        /// </summary>
        public static string ValidationPatternAlphabetSqSrEn {
            get {
                return ResourceManager.GetString("ValidationPatternAlphabetSqSrEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only a-zA-ZçÇëËčČćĆđĐšŠžŽĞğÖöŞşÜüIıİi are allowed.
        /// </summary>
        public static string ValidationRegexLetters {
            get {
                return ResourceManager.GetString("ValidationRegexLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        public static string ValidationRequired {
            get {
                return ResourceManager.GetString("ValidationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uppercase letters only.
        /// </summary>
        public static string ValidationUpperCaseLetters {
            get {
                return ResourceManager.GetString("ValidationUpperCaseLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL cant have those characters.
        /// </summary>
        public static string ValidationUrlPattern {
            get {
                return ResourceManager.GetString("ValidationUrlPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username characters entered A-Z 0-9 and . is allowed.
        /// </summary>
        public static string ValidationUsername {
            get {
                return ResourceManager.GetString("ValidationUsername", resourceCulture);
            }
        }
    }
}
